apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterbulb-monitor-sa
  namespace: clusterbulb-monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterbulb-monitor-clusterrole
rules:
- apiGroups: [""]
  resources:
    - nodes
    - pods
    - events
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterbulb-monitor-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: clusterbulb-monitor-sa
  namespace: clusterbulb-monitor
roleRef:
  kind: ClusterRole
  name: clusterbulb-monitor-clusterrole
  apiGroup: rbac.authorization.k8s.io
