apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:yvu/nnz2Io6xMavh21pstLuCIaVviMZt9SavVt88nKjoCTBRXYDq91VAKPCPpW617NpnfHEw7OY=,iv:q4DV5HuUBTW5uXAv/LZ/oxvnf9c3ZPo8NTbkOmOBis0=,tag:ZVzRoK4zZIDNgNe6ic4pPQ==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age1mkghc2qu2mgac8wjnhea6dduerg4k2g0hp0r7see43ukc2vtsfzs9h69sa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcHR4eHJ5aWxhc2tVNmxn
            ZENxeEFzS2xEQy9wbS9maGlidEZoc0l2dVgwCnpCajBHbjZnakxJTXVxcGdOYzV4
            amtqOENtSUttRlh5d3lZeHZnRVJWK2sKLS0tIDB6UzlBUTZFNTVrOFNBWS81eExo
            aU5XYjZUZkpUVUZaTm9JM09FaGVXalEKOhJgnPt6wT1kYHMTrEbQ1UnA00PlFvXh
            D5VT/cv6M4kXxOfmiMdCHnjNdBTnQJWulZKj8bujUeNUY4ump2QwCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T14:37:01Z"
    mac: ENC[AES256_GCM,data:agpGSIci86mrdZDeIzYnq/Vmqc0DDPH+j15mDsmcTnLR18EtK9eKsGmwtSXMu7U/4lmJOv/tmLH1gPB09XtmponDPTya0SwPIAyRw2xBDYehwXYd/oIzvFalL6SNTAzmiszxeI46ExGsw1cBPtJmMRpIAScZ3lE+L7wH2K3NuAE=,iv:GWnpT3eWcWIjeHpvu9CtcMknv6w9LBd7k7LStQWZbJ8=,tag:vtIvz4UG/IBuxh7yMeOHTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
