apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:/ZUDbdTfuXeep+DAAHirEYVV7OQ9rJH9SiIUBrhK0hH7hrE7LWbBQ1itRo7ouxUW5FxnhEtSa/4=,iv:ncLdOXYxRfuW54PdL/pJ7D+W/GsnR47iCI0sO/tOB0I=,tag:TBqBdgg/u/o+5F3Gzkpr/g==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age182ptu7w6gaa8xeq52p5wd493t07qducqw4husg0z6hyh97jdsf6s3y4gfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRm1WR0ZOL2F1eTlHME1a
            YVZPVnJQL2ZKOUV0YjNUYmxTNWZRQjY4WUc4CmFoUmkzdmNTKzFudXYwYWZzU1Bk
            cjE2TjlHcTZVNFdUclJNWXRDZnRqZFUKLS0tIHRGa1g0dGh4WDIrUjl0ZURjcUxQ
            amFyZzdLQVlpd0diN0g3YWo1Umxqd1UK7uuUfUCCsrjq7YkxGdSvs9+0HJRcUn2N
            nftASJ3LBGhyT3fChKfU5OxXnZgqwdMLgwI44ZqUqqsI2U2z03yrHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T15:34:42Z"
    mac: ENC[AES256_GCM,data:xeGUZkxaSZ1GHTDE2vazpv9wUrkqUOuK6DeiVuGGAagjZjAA0+N8AoRFVcFWRY5unR4i61i0Fh7mbPJM2sqijVClw3/QiH1DXMysfxN6LNQrn7RHVppEdw/DnLCQM2/lgI8voJuR4apSN/wti8tsuKhyDtDB03CpNtQSPaY7RGg=,iv:eN4ULMpT4oBfTboX4mzWNDbhMfPmY78ozNfn37d0QJI=,tag:vZjR2pztX5Zl03gmfpAaUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
