apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:PEnxaa/qMmPXecGbeY4wpEkMnaCgMp7jlbUs79FqR/oTwZgcIGl2mkkjVktxBrK4FILFbuX2TNI=,iv:OVx9CoSQTOuq6RAiWKKs2xTC8eG3qAZSSWzt1PXt6yE=,tag:qj+bpzW2uWgr8L9M8dnFOA==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age17v8x6aajgg88dsqgxe2rnv06amyatz0e36fqrmkvyg0dczk6xces2hv45r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUlhoTGtkNmkrcU95SDY5
            cFpWMWl3d2FndkVPNzMzSlFBSnprUWZxTERVCkpxMGhVYUxReU51b25GcE1MYnBG
            VTVRbDFrdUZFZFc1ZGNFMG5QVEl1UmMKLS0tIEtyaStzMkdCUWpxdmk2NU1Ndjk0
            dDZaUXNMVGlBSE1pY0FQSk9xU3BpSk0KqjE93MN2RUk1AFfeP6xZheIOEKpIFkIe
            pR6IU1hdpCRowPwUms+6xe/yHQYjJKIitN3WBZSN2Z6Xo5BfLnXwlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T13:58:40Z"
    mac: ENC[AES256_GCM,data:iY7wsVtuvuel+1PV4dLP6kYWIGpepUShGbCmmv1GtWiplcwrtYUCMMFuZ6eTk5LrECJ52eXIdo/zqrexd6akU4BnXDnlixCyREMqwf44tgwDk36twJ3fhwOXmS7IkNl1HDAK45XO51uQ+9/fdxb/IrZFE859xJhhsZRYZZhNeEs=,iv:i3KHHL9I9Tfxu2yMudRIco4GBHkvUwujM3FbT4Bb8ds=,tag:vOt2hudhrcv5SJF6hGWGQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
